### ISSUE TITLE
Casper testrun results not reported to TestRail

### ISSUE THREAD

**Issue by jessetab** [tableau-mkt/testrail-cli#8]
Casper test results (casper_xunit.xml) are currently not being reported to TestRail after test runs that contain test failures on Travis.

See build: https://magnum.travis-ci.com/tableau-mkt/www7/builds/16346346

$TESTRAIL report --runId=$TESTRAIL_RUNID --file=$HOME/casper_xunit.xml
/home/travis/build/tableau-mkt/www7/node_modules/testrail-cli/node_modules/promise/lib/done.js:10
      throw err;
            ^
TypeError: Cannot read property 'length' of undefined
    at Html5Entities.decode (/home/travis/build/tableau-mkt/www7/node_modules/testrail-cli/node_modules/html-entities/lib/html5-entities.js:18:12)
    at xml.root.children.forEach.testSuite.root (/home/travis/build/tableau-mkt/www7/node_modules/testrail-cli/src/core.js:193:55)
    at Array.forEach (native)
    at parseXmlIntoCaseResults (/home/travis/build/tableau-mkt/www7/node_modules/testrail-cli/src/core.js:172:33)
    at /home/travis/build/tableau-mkt/www7/node_modules/testrail-cli/src/core.js:212:17
    at Array.forEach (native)
    at parseXmlIntoCaseResults (/home/travis/build/tableau-mkt/www7/node_modules/testrail-cli/src/core.js:209:33)
    at /home/travis/build/tableau-mkt/www7/node_modules/testrail-cli/src/core.js:221:13
    at Array.forEach (native)
    at /home/travis/build/tableau-mkt/www7/node_modules/testrail-cli/src/core.js:166:22

**Comment by iamEAP** [comment]
Published v0.2.1, including the fix from #9.
